# Generated by Django 2.2.17 on 2023-04-04 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('desc', models.CharField(max_length=300, verbose_name='Course Description')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Learn Times (mins)')),
                ('degree', models.CharField(choices=[('cj', 'Easy'), ('zj', 'Medium'), ('gj', 'Hard')], max_length=2, verbose_name='Degree')),
                ('students', models.IntegerField(default=0, verbose_name='Number of Students')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Number of Favorites')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Clicks')),
                ('notice', models.CharField(default='', max_length=300, verbose_name='Course Announcement')),
                ('category', models.CharField(default='后端开发', max_length=20, verbose_name='Course Category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='Course Tag')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='MUSTKNOW')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='Teacher Tell')),
                ('is_classics', models.BooleanField(default=False, verbose_name='Classical')),
                ('detail', models.TextField(verbose_name='Course Details')),
                ('is_banner', models.BooleanField(default=False, verbose_name='isBanner')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='Course Image')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Course Information',
                'verbose_name_plural': 'Course Information',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=100, verbose_name='Lesson Name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Course Duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=100, verbose_name='Video Name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Duration')),
                ('url', models.CharField(max_length=1000, verbose_name='URL')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='File Location')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resource',
            },
        ),
    ]
