# Generated by Django 4.1.7 on 2023-04-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id_alter_courseresource_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='file',
            new_name='download',
        ),
    ]
