# Generated by Django 4.1.7 on 2023-03-29 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=20, verbose_name='City Name')),
                ('desc', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=50, verbose_name='Organization Name')),
                ('desc', models.TextField()),
                ('tag', models.CharField(default='Nationwide Famous', max_length=10, verbose_name='Org Tag')),
                ('category', models.CharField(choices=[('pxjg', 'Organization'), ('gr', 'Individual'), ('gx', 'University')], default='pxjg', max_length=4, verbose_name='Organization Type')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Clicks')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Number of Favorites')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=150, verbose_name='Organization Address')),
                ('students', models.IntegerField(default=0, verbose_name='Number of Students')),
                ('course_nums', models.IntegerField(default=0, verbose_name='Number of Courses')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Course Organization',
                'verbose_name_plural': 'Course Organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=50, verbose_name="Teacher's Name")),
                ('work_years', models.IntegerField(default=0, verbose_name='YOE')),
                ('work_company', models.CharField(max_length=50, verbose_name='Employer')),
                ('work_position', models.CharField(max_length=50, verbose_name='Position')),
                ('points', models.CharField(max_length=50, verbose_name='Characters')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Clicks')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Favorites')),
                ('age', models.IntegerField(default=18, verbose_name='Age')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='Avatar')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.courseorg', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
