# Generated by Django 4.1.7 on 2023-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_city_id_alter_courseorg_id_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '课程机构', 'verbose_name_plural': '课程机构'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='是否金牌'),
        ),
    ]
